### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by laixintao** [sibson/redbeat#141]
Hi, it seems [fakeredis](https://github.com/jamesls/fakeredis) doesn't support the full command list of Redis, nor support redis-py's variables.

![image](https://user-images.githubusercontent.com/9675939/62032096-67fce980-b21b-11e9-9e6b-918f222f52a7.png)

Can we switch to CircleCI's Redis service? What do you think? @sibson  I am familiar with CircleCI.

**Comment by laixintao** [comment]
If you are ok with that, I can create a PR to fix test cases. It has been broken for so long.

**Comment by sibson** [comment]
I'd prefer to keep an option to use fakeredis for local dev but could be convinced otherwise.  I like fakeredis because it makes local dev easier, rather than ensuring there is a working Redis install available locally, and ensuring we're not interfering with other services.  I've no objection to using CircleCI Redis when its running tests in the CircleCI environment though, that would be lead to better dev/prod parity too.  I'm not sure how hard it would be to selectively use fakeredis.  It also seems fakeredis is becoming more hassle than it saves in which case I'm open to having a more complicated local dev story too.

I'd also be willing to consider deleting the offending test if it isn't adding a lot of value.  I'm not sure which one that is but it looks like something that is more core celery than redbeat specific.  Maybe we can skip core celery tests?

**Comment by sibson** [comment]
Also see, https://github.com/sibson/redbeat/pull/142

**Comment by laixintao** [comment]
Cool, I saw the CI was green now.
