### ISSUE TITLE
Collaboration on Redbeat schedule manager

### ISSUE THREAD

**Issue by pjaol** [sibson/redbeat#195]
@sibson this is a fantastic project, and honestly something that Celery should start copying.
I got stuck with an issue that many folks had which was viewing periodic tasks #https://github.com/celery/celery/issues/4535, and found some code in #155 that helped. 

I've started working on a simple web interface that exposed the scheduled tasks
![image](https://user-images.githubusercontent.com/490072/103943922-eb08bb80-5100-11eb-99f1-ddbf7f39619e.png)

Will make it public in the next few days when I can get someone to do a sanity check on it and I make it less embarrassing. 
Would there be any interest in collaboration on it? 
Am not looking at replacing flower, just plugging some holes that a few folks, myself included have.

**Comment by sibson** [comment]
Hey, this looks great.  I don't have time to contribute to your project but am happy to explore other ways to collaborate.

**Comment by pjaol** [comment]
Thanks Marc
I might have a couple of pull requests that would help the UI like a UUID on the RedBeatSchedulerEvents 
that would make updates easier to do. I'll flesh it out 

Here's the initial code base https://github.com/preftech/redbeat_manager

**Comment by sibson** [comment]
Sounds good, my guiding principle is minimize divergence from core celery.  This ensures the project continues to be maintainable and compatible with celery releases with minimal effort.

**Comment by sibson** [comment]
I'm going to close this issue, because I don't think there is anything I can action on it.  I'm happy to include a link to your project in the docs and would love to see it successful, observability of system state is super important.  I've not reviewed your code, so you may already have considered these, but security is something I'd be concerned about.  For example, what if the args/kwargs contain sensitive data, how to limit and audit access to the UI?  The screenshot above is great to help understand the project, it would be helpful to have in your projects' README too.
